### ISSUE TITLE
Use static site+domain to promote the project

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#7]
The link used in hackernews submission https://news.ycombinator.com/item?id=21613294 is:
https://github.com/beatcracker/toptout

I think it will be better to use dedicated page for promoting the project #6 , such as using github pages for hosting site built from static files in repo.
also github offer `something.github.io` as domain which can be used (or buy a domain?)

**Comment by beatcracker** [comment]
I had some vague thoughts about this, but nothing concrete yet.

**Comment by beatcracker** [comment]
It's still WIP, but https://beatcracker.github.io/toptout is up and we have an [API](https://beatcracker.github.io/toptout/swagger) now.

**Comment by emanuelb** [comment]
Can you make it to not depend on JavaScript? (it shows Loading... when JS is disabled) or to open a new issue about it to use Server Side Rendering instead of javascript.
Also visiting top domain: https://beatcracker.github.io/
will result in 404 error.

**Comment by beatcracker** [comment]
The site works by using [Docsify.js](https://docsify.js.org/) to render README directly from the GitHub repo. So unfortunately it wouldn't work without JavaScript enabled in the browser. I've actually tried [Hugo](https://gohugo.io/) first to generate static pages, but it didn't work out. I might try to implement this again this later, but Docsify is just too damn convenient :).

I'll try to add some HTML so it at least will show the message about JS being required and a link to the original repo.

Server-side rendering is probably out of the question since I'd like to keep this as simple as possible, but I'll try to find out if it is possible to pre-render Docsify to static files.

About https://beatcracker.github.io/ giving 404 - this is because I don't have a "user" GitHub pages site. Not sure if I need one, but I might put something there so it'll be less confusing.

**Comment by beatcracker** [comment]
It's alive! :shipit: 

- https://toptout.me

**Comment by emanuelb** [comment]
Closing this issue as site+domain https://toptout.me is working :+1: and promoting the project is discussed in issue: https://github.com/beatcracker/toptout/issues/6
